moneypenny:
  host: "rsp.lsst.ac.uk"

  ingress:
    enabled: true
    hosts:
      - host: rsp.lsst.ac.uk
        paths: ["/moneypenny"]
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "https://rsp.lsst.ac.uk/auth?scope=exec:admin"

  vault_secrets:
    enabled: true
    path: "secret/k8s_operator/roe/pull-secret"

