 
moneypenny:
  host: "tucson-teststand.lsst.codes"

  ingress:
    enabled: true
    hosts:
      - host: rsp.lsst.ac.uk
        paths: ["/moneypenny"]
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "https://rsp.lsst.ac.uk/auth?scope=admin:provision"

  vault_secrets:
    enabled: true
    path: "secret/k8s_operator/tucson-teststand.lsst.codes/pull-secret"

  orders: |
    commission:
      - name: initcommission
        image: lsstsqre/inituserhome
        securityContext:
          runAsUser: 0
          runAsNonRootUser: false
        volumeMounts:
        - mountPath: /homedirs
          name: homedirs
    retire:
      - name: farthing
        image: lsstsqre/farthing
        securityContext:
          runAsUser: 1000
          runAsNonRootUser: true
          allowPrivilegeEscalation: false
