moneypenny:
  host: "summit-lsp.lsst.codes"

  ingress:
    enabled: true
    hosts:
      - host: summit-lsp.lsst.codes
        paths: ["/moneypenny"]
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "https://summit-lsp.lsst.codes/auth?scope=exec:admin"

  vault_secrets:
    enabled: true
    path: "secret/k8s_operator/summit-lsp.lsst.codes/pull-secret"

  orders: |
    commission:
      - name: initcommission
        image: lsstsqre/inituserhome
        securityContext:
          runAsUser: 0
          runAsNonRootUser: false
        volumeMounts:
        - mountPath: /homedirs
          name: homedirs
    retire:
      - name: farthing
        image: lsstsqre/farthing
        securityContext:
          runAsUser: 1000
          runAsNonRootUser: true
          allowPrivilegeEscalation: false
    volumes:
      - name: homedirs
        nfs:
          server: nfs1.cp.lsst.org
          path: /jhome
