moneypenny:
  host: "base-lsp.lsst.codes"

  ingress:
    enabled: true
    hosts:
      - host: base-lsp.lsst.codes
        paths: ["/moneypenny"]
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "https://base-lsp.lsst.codes/auth?scope=exec:admin"

  vault_secrets:
    enabled: true
    path: "secret/k8s_operator/base-lsp.lsst.codes/pull-secret"

  orders: |
    commission:
      - name: initcommission
        image: lsstsqre/inituserhome
        securityContext:
          runAsUser: 0
          runAsNonRootUser: false
        volumeMounts:
        - mountPath: /homedirs
          name: homedirs
    retire:
      - name: farthing
        image: lsstsqre/farthing
        securityContext:
          runAsUser: 1000
          runAsNonRootUser: true
          allowPrivilegeEscalation: false
    volumes:
      - name: homedirs
        nfs:
          server: ddn-nfs.ls.lsst.org
          path: /lssr/user/staff/jhome
