moneypenny:
  host: "base-lsp.lsst.codes"

  ingress:
    enabled: true
    hosts:
      - host: base-lsp.lsst.codes
        paths: ["/moneypenny"]
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "https://base-lsp.lsst.codes/auth?scope=exec:admin"

  vault_secrets:
    enabled: true
    path: "secret/k8s_operator/base-lsp.lsst.codes/pull-secret"
