moneypenny:
  host: "lsst-lsp-stable.ncsa.illinois.edu"

  ingress:
    enabled: true
    hosts:
      - host: lsst-lsp-stable.ncsa.illinois.edu
        paths: ["/moneypenny"]
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "https://lsst-lsp-stable.ncsa.illinois.edu/auth?scope=admin:provision"

  vault_secrets:
    enabled: true
    path: "secret/k8s_operator/lsst-lsp-stable.ncsa.illinois.edu/pull-secret"

  orders: |
    commission:
      - name: farthing
        image: lsstsqre/farthing
        securityContext:
          runAsUser: 1000
          runAsNonRootUser: true
          allowPrivilegeEscalation: false
    retire:
      - name: farthing
        image: lsstsqre/farthing
        securityContext:
          runAsUser: 1000
          runAsNonRootUser: true
          allowPrivilegeEscalation: false
