moneypenny:
  host: "minikube.lsst.codes"

  ingress:
    enabled: true
    hosts:
      - host: minikube.lsst.codes
        paths: ["/moneypenny"]
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "https://minikube.lsst.codes/auth?scope=exec:admin"

  vault_secrets:
    enabled: true
    path: "secret/k8s_operator/minikube.lsst.codes/pull-secret"
