cadc-tap:
  pull_secret: 'pull-secret'
  tag: "1.0.16"
  use_mock_qserv: false
  qserv_host: "10.140.1.211:4040"

  host: "data.lsst.cloud"

  secrets:
    enabled: false

  vault_secrets:
    enabled: true
    path: 'secret/k8s_operator/data.lsst.cloud/tap'

  gcs_bucket: 'async-results.lsst.codes'
  gcs_bucket_url: 'http://async-results.lsst.codes'

pull-secret:
  enabled: true
  path: secret/k8s_operator/data.lsst.cloud/pull-secret
