cadc-tap:
  pull_secret: 'pull-secret'
  tag: "1.0.15"
  use_mock_qserv: true

  host: "minikube.lsst.codes"

  secrets:
    enabled: false

  vault_secrets:
    enabled: true
    path: 'secret/k8s_operator/minikube.lsst.codes/tap'

  gcs_bucket: 'async-results.lsst.codes'
  gcs_bucket_url: 'http://async-results.lsst.codes'

pull-secret:
  enabled: true
  path: secret/k8s_operator/minikube.lsst.codes/pull-secret
