cadc-tap:
  pull_secret: 'pull-secret'
  tag: "1.0.16"
  use_mock_qserv: true

  host: "rsp.lsst.ac.uk"

  secrets:
    enabled: false

  vault_secrets:
    enabled: true
    path: 'secret/k8s_operator/roe/tap'

  gcs_bucket: 'async-results.lsst.codes'
  gcs_bucket_url: 'http://async-results.lsst.codes'

pull-secret:
  enabled: true
  path: secret/k8s_operator/roe/pull-secret

