cadc-tap-postgres:
  pull_secret: 'pull-secret'
  tag: "1.0"
  host: "gold-leader.lsst.codes"

  secrets:
    enabled: false

  vault_secrets:
    enabled: true
    path: 'secret/k8s_operator/gold-leader.lsst.codes/tap'

  gcs_bucket: 'async-results.lsst.codes'
  gcs_bucket_url: 'http://async-results.lsst.codes'

pull-secret:
  enabled: true
  path: secret/k8s_operator/gold-leader.lsst.codes/pull-secret
