cadc-tap-postgres:
  tag: "1.0"
  host: "lspdev.ddns.net"

  secrets:
    enabled: false

  vault_secrets:
    enabled: true
    path: 'secret/k8s_operator/roe/tap'

  gcs_bucket: 'lspdev.ddns.net'
  gcs_bucket_url: 'http://lspdev.ddns.net'
