environment: int
fqdn: lsst-lsp-int.ncsa.illinois.edu
vault_path_prefix: secret/k8s_operator/lsst-lsp-int.lsst.codes

argo:
  enabled: true
cachemachine:
  enabled: true
cert_issuer:
  enabled: false
cert_manager:
  enabled: false
chronograf:
  enabled: false
exposurelog:
  enabled: false
gafaelfawr:
  enabled: true
influxdb:
  enabled: false
kapacitor:
  enabled: false
logging:
  enabled: true
mobu:
  enabled: true
moneypenny:
  enabled: true
ingress_nginx:
  enabled: false
nublado2:
  enabled: true
obstap:
  enabled: true
portal:
  enabled: true
postgres:
  enabled: true
rancher_external_ip_webhook:
  enabled: false
squareone:
  enabled: true
squash_api:
  enabled: false
tap:
  enabled: true
vault_secrets_operator:
  enabled: true
