environment: base

argo:
  enabled: true
cert_issuer:
  enabled: true
cert_manager:
  enabled: false
chronograf:
  enabled: false
exposurelog:
  enabled: false
gafaelfawr:
  enabled: true
influxdb:
  enabled: false
kapacitor:
  enabled: false
landing_page:
  enabled: true
logging:
  enabled: false
mobu:
  enabled: false
ingress_nginx:
  enabled: false
nublado:
  enabled: true
obstap:
  enabled: false
portal:
  enabled: true
postgres:
  enabled: true
rancher_external_ip_webhook:
  enabled: false
squash_api:
  enabled: false
tap:
  enabled: false
vault_secrets_operator:
  enabled: true
