environment: squash-sandbox
fqdn: squash-sandbox.lsst.codes
vault_path_prefix: secret/k8s_operator/squash-sandbox.lsst.codes

argo:
  enabled: false
cert_issuer:
  enabled: true
cert_manager:
  enabled: true
chronograf:
  enabled: true
exposurelog:
  enabled: false
gafaelfawr:
  enabled: true
influxdb:
  enabled: true
kapacitor:
  enabled: true
logging:
  enabled: false
mobu:
  enabled: false
moneypenny:
  enabled: false
ingress_nginx:
  enabled: true
nublado2:
  enabled: false
obstap:
  enabled: false
portal:
  enabled: false
postgres:
  enabled: true
rancher_external_ip_webhook:
  enabled: true
squareone:
  enabled: false
squash_api:
  enabled: true
tap:
  enabled: false
vault_secrets_operator:
  enabled: true
