environment: bleed

argo:
  enabled: true
cachemachine:
  enabled: true
cert_issuer:
  enabled: true
cert_manager:
  enabled: true
chronograf:
  enabled: false
exposurelog:
  enabled: true
gafaelfawr:
  enabled: true
influxdb:
  enabled: false
kapacitor:
  enabled: false
landing_page:
  enabled: true
logging:
  enabled: false
mobu:
  enabled: true
ingress_nginx:
  enabled: true
nublado:
  enabled: true
nublado2:
  enabled: true
obstap:
  enabled: true
portal:
  enabled: true
postgres:
  enabled: true
squash_api:
  enabled: false
tap:
  enabled: true
vault_secrets_operator:
  enabled: true
