environment: summit
fqdn: summit-lsp.lsst.codes
vault_path_prefix: secret/k8s_operator/summit-lsp.lsst.codes

argo:
  enabled: true
cert_issuer:
  enabled: true
cert_manager:
  enabled: true
chronograf:
  enabled: false
exposurelog:
  enabled: true
gafaelfawr:
  enabled: true
influxdb:
  enabled: false
kapacitor:
  enabled: false
landing_page:
  enabled: true
logging:
  enabled: false
mobu:
  enabled: false
moneypenny:
  enabled: true
ingress_nginx:
  enabled: true
nublado:
  enabled: true
obstap:
  enabled: false
portal:
  enabled: true
postgres:
  enabled: true
rancher_external_ip_webhook:
  enabled: false
squash_api:
  enabled: false
tap:
  enabled: false
vault_secrets_operator:
  enabled: true
