environment: tucson-teststand
fqdn: tucson-teststand.lsst.codes
vault_path_prefix: secret/k8s_operator/tucson-teststand.lsst.codes

argo:
  enabled: true
cachemachine:
  enabled: true
cert_issuer:
  enabled: true
cert_manager:
  enabled: true
chronograf:
  enabled: false
exposurelog:
  enabled: false
gafaelfawr:
  enabled: true
influxdb:
  enabled: false
kapacitor:
  enabled: false
logging:
  enabled: false
mobu:
  enabled: false
moneypenny:
  enabled: true
ingress_nginx:
  enabled: true
nublado2:
  enabled: true
obstap:
  enabled: false
portal:
  enabled: false
postgres:
  enabled: true
rancher_external_ip_webhook:
  enabled: true
squareone:
  enabled: true
squash_api:
  enabled: false
tap:
  enabled: false
vault_secrets_operator:
  enabled: true
