environment: roe

argo:
  enabled: true
cert_issuer:
  enabled: false
cert_manager:
  enabled: false
chronograf:
  enabled: false
exposurelog:
  enabled: false
gafaelfawr:
  enabled: true
influxdb:
  enabled: false
kapacitor:
  enabled: false
landing_page:
  enabled: true
logging:
  enabled: false
mobu:
  enabled: true
nginx_ingress:
  enabled: true
nublado:
  enabled: true
obstap:
  enabled: true
portal:
  enabled: true
postgres:
  enabled: true
squash_api:
  enabled: false
tap:
  enabled: true
vault_secrets_operator:
  enabled: true
