argo:
  enabled: false
cachemachine:
  enabled: false
cert_issuer:
  enabled: false
cert_manager:
  enabled: false
chronograf:
  enabled: false
exposurelog:
  enabled: false
gafaelfawr:
  enabled: false
influxdb:
  enabled: false
ingress_nginx:
  enabled: false
kapacitor:
  enabled: false
landing_page:
  enabled: false
logging:
  enabled: false
mobu:
  enabled: false
moneypenny:
  enabled: false
nublado:
  enabled: false
nublado2:
  enabled: false
obstap:
  enabled: false
portal:
  enabled: false
postgres:
  enabled: false
rancher_external_ip_webhook:
  enabled: false
squash_api:
  enabled: false
tap:
  enabled: false
vault_secrets_operator:
  enabled: false

repoURL: https://github.com/stvoutsin/lsp-deploy.git
revision: HEAD
onepassword_uuid: "dg5afgiadsffeklfr6jykqymeu"
