gafaelfawr:
  pull_secret: 'pull-secret'
  host: base-lsp.lsst.codes
  ingress:
    host: base-lsp.lsst.codes
  vault_secrets_path: "secret/k8s_operator/base-lsp.lsst.codes/gafaelfawr"

  # Session length and token expiration (in minutes).
  issuer:
    exp_minutes: 43200  # 30 days

  # Use GitHub authentication.
  github:
    client_id: ec88b9b897f302b620d1

  # Allow access by GitHub team.
  group_mapping:
    "exec:admin":
      - "lsst-sqre-square"
    "exec:user":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-ts-base-access"
    "read:workspace":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-ts-base-access"
    "read:workspace/user":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-ts-base-access"
    "write:workspace/user":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-ts-base-access"
    "exec:portal":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-ts-base-access"
    "exec:notebook":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-ts-base-access"
    "read:tap":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-ts-base-access"
    "read:image":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-ts-base-access"

pull-secret:
  enabled: true
  path: secret/k8s_operator/base-lsp.lsst.codes/pull-secret
