gafaelfawr:
  pull_secret: 'pull-secret'
  host: lsst-lsp-stable.ncsa.illinois.edu
  ingress:
    host: lsst-lsp-stable.ncsa.illinois.edu
  vault_secrets_path: "secret/k8s_operator/lsst-lsp-stable.ncsa.illinois.edu/gafaelfawr"

  # IP range used by the cluster, used to determine the true client IP for
  # logging.
  proxies:
    - "41.142.182.128/26"

  # Session length and token expiration (in minutes).
  issuer:
    exp_minutes: 43200  # 30 days

  # PVC for the Redis volume.
  redis_claim: "auth-redis-volume-claim"

  # Use CILogon authentication.
  cilogon:
    client_id: "cilogon:/client_id/7ae419868b97e81644ced9886ffbcec"
    redirect_url: "https://lsst-lsp-stable.ncsa.illinois.edu/oauth2/callback"
    login_params:
      skin: "LSST"

pull-secret:
  enabled: true
  path: secret/k8s_operator/lsst-lsp-stable.ncsa.illinois.edu/pull-secret
