gafaelfawr:
  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: "tucson-teststand.lsst.codes"
  vaultSecretsPath: "secret/k8s_operator/tucson-teststand.lsst.codes/gafaelfawr"

  # Reset token storage on every Redis restart for now.  This should change to
  # use persistent volumes once we can coordinate that.
  redis:
    persistence:
      enabled: false

  config:
    host: "tucson-teststand.lsst.codes"

    # Use GitHub authentication.
    github:
      clientId: "49533cbd8a8079730dcf"

    # Allow access by GitHub team.
    group_mapping:
      "exec:admin":
        - "lsst-sqre-square"
      "exec:notebook":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
        - "lsst-ts-base-access"
      "exec:portal":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
        - "lsst-ts-base-access"
      "exec:user":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
        - "lsst-ts-base-access"
      "read:tap":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
        - "lsst-ts-base-access"

pull-secret:
  enabled: true
  path: "secret/k8s_operator/tucson-teststand.lsst.codes/pull-secret"
