gafaelfawr:
  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: "summit-lsp.lsst.codes"
  vaultSecretsPath: "secret/k8s_operator/summit-lsp.lsst.codes/gafaelfawr"

  # Reset token storage on every Redis restart for now.  This should change to
  # use persistent volumes once we can coordinate that.
  redis:
    persistence:
      enabled: false

  config:
    host: "summit-lsp.lsst.codes"

    # Use GitHub authentication.
    github:
      clientId: "220d64cbf46f9d2b7873"

    # Allow access by GitHub team.
    groupMapping:
      "exec:admin":
        - "lsst-sqre-square"
      "exec:notebook":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
        - "lsst-ts-summit-access"
      "exec:portal":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
        - "lsst-ts-summit-access"
      "exec:user":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
        - "lsst-ts-summit-access"
      "read:tap":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
        - "lsst-ts-summit-access"

pull-secret:
  enabled: true
  path: "secret/k8s_operator/summit-lsp.lsst.codes/pull-secret"
