gafaelfawr:
  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: "red-five.lsst.codes"
  vaultSecretsPath: "secret/k8s_operator/red-five.lsst.codes/gafaelfawr"

  # Reset token storage on every Redis restart.
  redis:
    persistence:
      enabled: false

  config:
    host: "red-five.lsst.codes"
    databaseUrl: "postgresql://gafaelfawr@postgres.postgres/gafaelfawr"

    # Disabled but kept so that the client ID is easily accessible.
    # github:
    #   clientId: "a19e79298a352f3e5650"

    # Use CILogon authentication.
    cilogon:
      clientId: "cilogon:/client_id/51ea95a5fac24d5a6f33e658d7d77d2a"
      loginParams:
        skin: "LSST"

    # Use NCSA groups to determine token scopes.
    groupMapping:
      "admin:provision": ["lsst_int_lsp_admin"]
      "exec:admin": ["lsst_int_lsp_admin"]
      "exec:notebook": ["lsst_int_lspdev"]
      "exec:portal": ["lsst_int_lspdev"]
      "read:tap": ["lsst_int_lspdev"]

    initialAdmins:
      - "afausti"
      - "athornto"
      - "cbanek"
      - "frossie"
      - "jsick"
      - "krughoff"
      - "rra"

pull-secret:
  enabled: true
  path: "secret/k8s_operator/red-five.lsst.codes/pull-secret"
