gafaelfawr:
  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: "rsp.lsst.ac.uk"
  vaultSecretsPath: "secret/k8s_operator/roe/gafaelfawr"

  # Session length and token expiration (in minutes).
  issuer:
    exp_minutes: 43200  # 30 days

  github:
    client_id: 10172b4db1b67ee31620

  config:
    host: "rsp.lsst.ac.uk"

    github:
      clientId: "65b6333a066375091548"

    # Allow access by GitHub team.
    groupMapping:
      "exec:admin":
        - "lsp-uk-dev"
      "exec:notebook":
        - "lsp-uk-dev"
      "read:workspace":
        - "lsp-uk-dev"
      "read:workspace/user":
        - "lsp-uk-dev"
      "write:workspace/user":
      "exec:portal":
        - "lsp-uk-dev"
      "exec:user":
        - "lsp-uk-dev"
      "read:tap":
        - "lsp-uk-dev"
      "read:image":
        - "lsp-uk-dev"

pull-secret:
  enabled: true
  path: secret/k8s_operator/roe/pull-secret
