gafaelfawr:
  pull_secret: 'pull-secret'
  host: data.lsst.cloud
  ingress:
    host: data.lsst.cloud
  vault_secrets_path: "secret/k8s_operator/data.lsst.cloud/gafaelfawr"

  # Do not specify ingress.host because we're using the wildcard virtual host.

  # Session length and token expiration (in minutes).
  issuer:
    exp_minutes: 43200  # 30 days

  github:
    client_id: 65b6333a066375091548

  # Allow access by GitHub team.
  group_mapping:
    "exec:admin":
      - "lsst-sqre-square"
    "exec:user":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-data-management"
    "read:workspace":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-data-management"
    "read:workspace/user":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-data-management"
    "write:workspace/user":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-data-management"
    "exec:portal":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-data-management"
    "exec:notebook":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-data-management"
    "read:tap":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-data-management"
    "read:image":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
      - "lsst-data-management"

pull-secret:
  enabled: true
  path: secret/k8s_operator/data.lsst.cloud/pull-secret
