gafaelfawr:
  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: "data.lsst.cloud"
  vaultSecretsPath: "secret/k8s_operator/data.lsst.cloud/gafaelfawr"

  # Use the CSI storage class so that we can use snapshots.
  redis:
    persistence:
      storageClass: "standard-rwo"

  config:
    host: "data.lsst.cloud"

    github:
      clientId: "65b6333a066375091548"

    # Allow access by GitHub team.
    groupMapping:
      "exec:admin":
        - "lsst-sqre-square"
      "exec:notebook":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
        - "lsst-data-management"
      "exec:portal":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
        - "lsst-data-management"
      "exec:user":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
        - "lsst-data-management"
      "read:tap":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
        - "lsst-data-management"

pull-secret:
  enabled: true
  path: "secret/k8s_operator/data.lsst.cloud/pull-secret"
