gafaelfawr:
  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: "data-dev.lsst.cloud"
  vaultSecretsPath: "secret/k8s_operator/data-dev.lsst.cloud/gafaelfawr"

  # Enable the frontend NetworkPolicy.
  networkPolicy:
    enabled: true

  # Use the CSI storage class so that we can use snapshots.
  redis:
    persistence:
      storageClass: "standard-rwo"

  config:
    host: "data-dev.lsst.cloud"
    databaseUrl: "postgresql://gafaelfawr@localhost/gafaelfawr"

    github:
      clientId: "f46555b3f4c524e764ac"

    # Allow access by GitHub team.
    groupMapping:
      "admin:provision":
        - "lsst-sqre-square"
      "exec:admin":
        - "lsst-sqre-square"
      "exec:notebook":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
      "exec:portal":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
      "read:tap":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"

    initialAdmins:
      - "afausti"
      - "athornton"
      - "cbanek"
      - "frossie"
      - "jonathansick"
      - "rra"
      - "simonkrughoff"

  cloudsql:
    enabled: true
    instanceConnectionName: "science-platform-dev-7696:us-central1:science-platform-dev-e9e11de2"
    serviceAccount: "gafaelfawr@science-platform-dev-7696.iam.gserviceaccount.com"

pull-secret:
  enabled: true
  path: "secret/k8s_operator/data-dev.lsst.cloud/pull-secret"
