gafaelfawr:
  host: data-dev.lsst.cloud
  ingress:
    host: data-dev.lsst.cloud
  vault_secrets_path: "secret/k8s_operator/data-dev.lsst.cloud/gafaelfawr"

  # Do not specify ingress.host because we're using the wildcard virtual host.

  # Session length and token expiration (in minutes).
  issuer:
    exp_minutes: 43200  # 30 days

  github:
    client_id: f46555b3f4c524e764ac

  # Allow access by GitHub team.
  group_mapping:
    "exec:admin":
      - "lsst-sqre-square"
    "exec:user":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
    "read:workspace":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
    "read:workspace/user":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
    "write:workspace/user":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
    "exec:portal":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
    "exec:notebook":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
    "read:tap":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
    "read:image":
      - "lsst-sqre-square"
      - "lsst-sqre-friends"
