gafaelfawr:
  imagePullSecrets:
    - name: "pull-secret"
  ingress:
    host: "base-lsp.lsst.codes"
  vaultSecretsPath: "secret/k8s_operator/base-lsp.lsst.codes/gafaelfawr"

  # Reset token storage on every Redis restart for now.  This should change to
  # use persistent volumes once we can coordinate that.
  redis:
    persistence:
      enabled: false

  config:
    host: "base-lsp.lsst.codes"

    github:
      clientId: "ec88b9b897f302b620d1"

    # Allow access by GitHub team.
    groupMapping:
      "exec:admin":
        - "lsst-sqre-square"
      "exec:notebook":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
        - "lsst-ts-base-access"
      "exec:portal":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
        - "lsst-ts-base-access"
      "exec:user":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
        - "lsst-ts-base-access"
      "read:tap":
        - "lsst-sqre-square"
        - "lsst-sqre-friends"
        - "lsst-ts-base-access"

pull-secret:
  enabled: true
  path: "secret/k8s_operator/base-lsp.lsst.codes/pull-secret"
