gafaelfawr:
  pull_secret: 'pull-secret'
  host: rogue-two.lsst.codes
  ingress:
    host: rogue-two.lsst.codes
  vault_secrets_path: "secret/k8s_operator/rogue-two.lsst.codes/gafaelfawr"

  # Do not specify ingress.host because we're using the wildcard virtual host.

  # Session length and token expiration (in minutes).
  issuer:
    exp_minutes: 43200  # 30 days

  # Disabled but kept so that the client ID is easily accessible.
  # github:
  #   client_id: a19e79298a352f3e5650

  # Use CILogon authentication.
  cilogon:
    client_id: "cilogon:/client_id/15352006fec091e45e1425bce7c3c352"
    login_params:
      skin: "LSST"

pull-secret:
  enabled: true
  path: secret/k8s_operator/rogue-two.lsst.codes/pull-secret
