gafaelfawr:
  pull_secret: 'pull-secret'
  host: gold-leader.lsst.codes
  ingress:
    host: gold-leader.lsst.codes
  vault_secrets_path: "secret/k8s_operator/gold-leader.lsst.codes/gafaelfawr"

  # Do not specify ingress.host because we're using the wildcard virtual host.

  # Session length and token expiration (in minutes).
  issuer:
    exp_minutes: 43200  # 30 days

  # Disabled but kept so that the client ID is easily accessible.
  # github:
  #   client_id: a19e79298a352f3e5650

  # Use CILogon authentication.
  cilogon:
    client_id: "cilogon:/client_id/537ab5b211d0ddacb05964e5adf9a4dc"
    login_params:
      skin: "LSST"

pull-secret:
  enabled: true
  path: secret/k8s_operator/gold-leader.lsst.codes/pull-secret
