{{- if .Values.gafaelfawr.enabled -}}
apiVersion: v1
kind: Namespace
metadata:
  name: gafaelfawr
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gafaelfawr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gafaelfawr
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/gafaelfawr
    repoURL: https://github.com/stvoutsin/lsp-deploy.git
    targetRevision: {{ .Values.gafaelfawr.revision }}
    helm:
      valueFiles:
        - values-{{ .Values.environment }}.yaml
{{- end -}}
