{{- if .Values.nublado.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nublado-users
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nublado-users
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/nublado-users
    repoURL: https://github.com/stvoutsin/lsp-deploy.git
    targetRevision: {{ .Values.nublado.revision }}
{{- end -}}
