{{- if .Values.obstap.enabled -}}
apiVersion: v1
kind: Namespace
metadata:
  name: obstap
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obstap
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: obstap
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/obstap
    repoURL: https://github.com/stvoutsin/lsp-deploy.git
    targetRevision: {{ .Values.obstap.revision }}
    helm:
      valueFiles:
        - values-{{ .Values.environment }}.yaml
{{- end -}}
