{{- if .Values.rancher_external_ip_webhook.enabled -}}
apiVersion: v1
kind: Namespace
metadata:
  name: rancher-external-ip-webhook
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-external-ip-webhook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rancher-external-ip-webhook
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/rancher-external-ip-webhook
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.revision }}
    helm:
      valueFiles:
        - values-{{ .Values.environment }}.yaml
{{- end -}}
