squareone:
  ingress:
    host: "lsst-nts-k8s.ncsa.illinois.edu"
  imagePullSecrets:
    - name: "pull-secret"
  config:
    siteName: "Rubin Science Platform @ NTS"

pull-secret:
  enabled: true
  path: secret/k8s_operator/lsst-nts-k8s.ncsa.illinois.edu/pull-secret
