init:
  serviceAccount: "nublado-hub"

argo:
  server:
    enabled: true
    baseHref: "/workflows/"
  controller:
    containerRuntimeExecutor: "k8sapi"

pull-secret:
  enabled: true
  path: secret/k8s_operator/data-dev.lsst.cloud/pull-secret
