ingress-nginx:
  controller:
    config:
      compute-full-forwarded-for: "true"
      large-client-header-buffers: "4 64k"
      proxy-body-size: "100m"
      proxy-buffer-size: "64k"
      ssl-redirect: "true"
      use-forwarded-headers: "true"
    service:
      externalTrafficPolicy: Local
      loadBalancerIP: "140.252.34.101"
    podLabels:
      hub.jupyter.org/network-access-proxy-http: "true"

vault_certificate:
  enabled: false

pull-secret:
  enabled: true
  path: secret/k8s_operator/tucson-teststand.lsst.codes/pull-secret
