postgres:
  pull_secret: 'pull-secret'
  vault_secrets:
    path: 'secret/k8s_operator/lsst-nts-k8s.ncsa.illinois.edu/postgres'
  debug: 'true'
  jupyterhub_db:
    user: 'jovyan'
    db: 'jupyterhub'
  exposurelog_db:
    user: 'exposurelog'
    db: 'exposurelog'
  postgres_storage_class: 'manual'
  volume_name: 'postgres-data-volume'

pull-secret:
  enabled: true
  path: secret/k8s_operator/lsst-nts-k8s.ncsa.illinois.edu/pull-secret
