postgres:
  vault_secrets:
    path: 'secret/k8s_operator/lspdev.ddns.net/postgres'
  debug: 'true'
  jupyterhub_db:
    user: 'jovyan'
    db: 'jupyterhub'
  exposurelog_db:
    user: 'exposurelog'
    db: 'exposurelog'
  image:
    tag: '0.0.2'
  postgres_storage_class: 'standard'



