postgres:
  pull_secret: 'pull-secret'
  vault_secrets:
    path: 'secret/k8s_operator/roe/postgres'
  debug: 'true'
  jupyterhub_db:
    user: 'jovyan'
    db: 'jupyterhub'
  gafaelfawr_db:
    user: 'gafaelfawr'
    db: 'gafaelfawr'
  postgres_storage_class: 'standard'

  image:
    tag: '0.0.3'
    
pull-secret:
  enabled: true
  path: secret/k8s_operator/roe/pull-secret
