mobu:
  pull_secret: 'pull-secret'
  gafaelfawr_secrets_path: "secret/k8s_operator/data-int.lsst.cloud/gafaelfawr"
  mobu_secrets_path: "secret/k8s_operator/data-int.lsst.cloud/mobu"
  environment_url: "https://data-int.lsst.cloud"
  host: "data-int.lsst.cloud"

pull-secret:
  enabled: true
  path: secret/k8s_operator/data-int.lsst.cloud/pull-secret
