mobu:
  pull_secret: 'pull-secret'
  mobu_secrets_path: "secret/k8s_operator/lsst-lsp-int.ncsa.illinois.edu/mobu"
  environment_url: "https://lsst-lsp-int.ncsa.illinois.edu"
  host: "lsst-lsp-int.ncsa.illinois.edu"

  ingress:
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "https://lsst-lsp-int.ncsa.illinois.edu/auth?scope=exec:admin&auth_type=basic"

pull-secret:
  enabled: true
  path: secret/k8s_operator/lsst-lsp-int.ncsa.illinois.edu/pull-secret
