mobu:
  pull_secret: 'pull-secret'
  mobu_secrets_path: "secret/k8s_operator/data-int.lsst.cloud/mobu"
  environment_url: "https://data-int.lsst.cloud"
  host: "data-int.lsst.cloud"

  ingress:
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "http://gafaelfawr.gafaelfawr.svc.cluster.local:8080/auth?scope=exec:admin&auth_type=basic"

pull-secret:
  enabled: true
  path: secret/k8s_operator/data-int.lsst.cloud/pull-secret
