mobu:
  pull_secret: 'pull-secret'
  gafaelfawr_secrets_path: "secret/k8s_operator/roe/gafaelfawr"
  mobu_secrets_path: "secret/k8s_operator/roe/mobu"
  environment_url: "https://rsp.lsst.ac.uk"
  host: "rsp.lsst.ac.uk"

  image:
    tag: master
    
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "http://gafaelfawr.gafaelfawr.svc.cluster.local:8080/auth?scope=exec:admin&auth_type=basic"
      
pull-secret:
  enabled: true
  path: secret/k8s_operator/roe/pull-secret
