mobu:
  gafaelfawr_secrets_path: "secret/k8s_operator/roe/gafaelfawr"
  mobu_secrets_path: "secret/k8s_operator/roe/mobu"
  environment_url: "https://lspdev.ddns.net:31337"
  host: "lspdev.ddns.net"

  image:
    tag: master
