mobu:
  pull_secret: 'pull-secret'
  gafaelfawr_secrets_path: "secret/k8s_operator/roe/gafaelfawr"
  mobu_secrets_path: "secret/k8s_operator/roe/mobu"
  environment_url: "https://rsp.lsst.ac.uk"
  host: "rsp.lsst.ac.uk"

  image:
    tag: master

pull-secret:
  enabled: true
  path: secret/k8s_operator/roe/pull-secret
