mobu:
  pull_secret: 'pull-secret'
  gafaelfawr_secrets_path: "secret/k8s_operator/lsst-lsp-stable.ncsa.illinois.edu/gafaelfawr"
  mobu_secrets_path: "secret/k8s_operator/lsst-lsp-stable.ncsa.illinois.edu/mobu"
  environment_url: "https://lsst-lsp-stable.ncsa.illinois.edu"
  host: "lsst-lsp-stable.ncsa.illinois.edu"

  ingress:
    annotations:
      nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Uid, X-Auth-Request-Token
      nginx.ingress.kubernetes.io/auth-url: "https://lsst-lsp-stable.ncsa.illinois.edu/auth?scope=exec:admin&auth_type=basic"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        auth_request_set $auth_token $upstream_http_x_auth_request_token;
        proxy_set_header Authorization "Bearer $auth_token";

pull-secret:
  enabled: true
  path: secret/k8s_operator/lsst-lsp-stable.ncsa.illinois.edu/pull-secret
