nublado:
  pull_secret: 'pull-secret'
  fqdn: lsst-lsp-int.ncsa.illinois.edu

  oauth_provider: 'jwt'
  gafaelfawr_secrets_path: 'secret/k8s_operator/lsst-lsp-int.ncsa.illinois.edu/gafaelfawr'

  lab:
    restrict_nodes: 'true'
    image:
      experimentals: 2
      dailies: 2
      cachefile: '/home/jovyan/repo-cache.json'

    resources:
      nodejs_max_mem: '6144'
      mb_per_cpu: 3072
      options_form_sizes: 'tiny,small,medium,large,huge,colossal'
      size_index: 2

  hub:
    persistent_home: false
    image: 'lsstsqre/sciplat-hub:0.35.4'

  wf:
    image: 'lsstsqre/wfdispatcher:0.4.4-pre3'
    ingress_ui:
      annotations:
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Token
        nginx.ingress.kubernetes.io/auth-signin: "https://lsst-lsp-int.ncsa.illinois.edu/login"
        nginx.ingress.kubernetes.io/auth-url: "https://lsst-lsp-int.ncsa.illinois.edu/auth?scope=exec:notebook"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Forwarded-Port 443;
          proxy_set_header X-Forwarded-Path /workflow;
          auth_request_set $auth_token $upstream_http_x_auth_request_token;
          proxy_set_header X-Portal-Authorization "Bearer $auth_token";
          error_page 403 = "/auth/forbidden?scope=exec:notebook";

  prepuller:
    image: 'lsstsqre/prepuller:0.9.4'
    schedule: "27 01,07,13,19 * * *"

  routes:
    soda: '/api/image/soda'
    external:
      instance: 'https://lsst-lsp-int.ncsa.illinois.edu'

  dask:
    restrict_nodes: 'true'

  vault_secrets:
    enabled: true
    path: secret/k8s_operator/lsst-lsp-int.ncsa.illinois.edu/nublado

  proxy:
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-signin: "https://lsst-lsp-int.ncsa.illinois.edu/login"
        nginx.ingress.kubernetes.io/auth-url: "https://lsst-lsp-int.ncsa.illinois.edu/auth?scope=exec:notebook"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Forwarded-Port 443;
          proxy_set_header X-Forwarded-Path /nb;
          auth_request_set $auth_token $upstream_http_x_auth_request_token;
          proxy_set_header X-Portal-Authorization "Bearer $auth_token";
          error_page 403 = "/auth/forbidden?scope=exec:notebook";
      host: lsst-lsp-int.ncsa.illinois.edu

  mountpoints: |
    [
      { "disabled": true,
        "mountpoint": "/example -- if it doesn't start with '/' we add it",
        "fileserver-host": "omit to use Hub settings",
        "fileserver-export": "defaults to '/exports<mountpoint>'",
        "hostpath": "if you're doing direct host mounts, e.g. GPFS w/o NFS",
        "mode": "rw or ro, defaults to 'ro'",
        "options": "mount options, e.g. 'local_lock=all'"
      },
      {
       "mountpoint": "/home",
        "mode": "rw",
        "hostpath": "/lsstdata/user/staff/jhome"
      },
      {
        "mountpoint": "/project",
        "mode": "rw",
        "hostpath": "/lsstdata/user/staff/project"
      },
      {
        "mountpoint": "/scratch",
        "mode": "rw",
        "hostpath": "/lsstdata/user/staff/scratch"
      },
      {
        "mountpoint": "/datasets",
        "mode": "ro",
        "hostpath": "/lsstdata/user/precursor_data/datasets"
      },
      {
        "mountpoint": "/lsstdata/offline/teststand",
        "mode": "ro",
        "hostpath": "/lsstdata/offline/teststand"
      }
    ]

  resourcemap: |
    [
        { "disabled": true,
          "user": "Username for user with custom resources",
          "group": "Groupname for group with custom resources",
          "resources": {
              "size_index": "integer representing which size container is default: 0 is smallest",
              "mem_quota": "integer, namespace quota size in MB",
              "cpu_quota": "integer, namespace quota CPU limit"
          }
        },
        { "group": "lsst_int_rspdev",
          "resources": {
              "size_index": 3,
              "mem_quota": 626688,
              "cpu_quota": 204
          }
        }
    ]

pull-secret:
  enabled: true
  path: secret/k8s_operator/lsst-lsp-int.ncsa.illinois.edu/pull-secret
