nublado:
  pull_secret: 'pull-secret'
  fqdn: kueyen-lsp.lsst.codes
  debug: 'true'
  oauth_provider: 'jwt'
  gafaelfawr_secrets_path: 'secret/k8s_operator/kueyen-lsp.lsst.codes/gafaelfawr'

  hub:
    image: 'lsstsqre/sciplat-hub:latest'

  wf:
    ingress_ui:
      annotations:
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Token
        nginx.ingress.kubernetes.io/auth-signin: "https://kueyen-lsp.lsst.codes/login"
        nginx.ingress.kubernetes.io/auth-url: "https://kueyen-lsp.lsst.codes/auth?scope=exec:notebook"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Forwarded-Port 443;
          proxy_set_header X-Forwarded-Path /workflow;
          auth_request_set $auth_token $upstream_http_x_auth_request_token;
          proxy_set_header X-Portal-Authorization "Bearer $auth_token";
          error_page 403 = "/auth/forbidden?scope=exec:notebook";

  lab:
    restrict_nodes: 'true'
    enable_multus: 'true'
    dds_domain: 'kueyen'
    dds_partition_prefix: 'kueyen'
    dds_interface: 'net1'
    image:
      experimentals: 0
      dailies: 0
      weeklies: 3
      releases: 1
      cachefile: '/home/jovyan/repo-cache.json'
      repo_name: 'kueyen-sal-sciplat-lab'

    resources:
      nodejs_max_mem: '6144'
      mb_per_cpu: 3172

  routes:
    soda: '/api/image/soda'
    external:
      instance: 'https://kueyen-lsp.lsst.codes'

  dask:
    restrict_nodes: 'true'
    max_workers: 50

  vault_secrets:
    enabled: true
    path: secret/k8s_operator/kueyen-lsp.lsst.codes/nublado

  proxy:
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-signin: "https://kueyen-lsp.lsst.codes/login"
        nginx.ingress.kubernetes.io/auth-url: "https://kueyen-lsp.lsst.codes/auth?scope=exec:notebook"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Forwarded-Port 443;
          proxy_set_header X-Forwarded-Path /nb;
          auth_request_set $auth_token $upstream_http_x_auth_request_token;
          proxy_set_header X-Portal-Authorization "Bearer $auth_token";
          error_page 403 = "/auth/forbidden?scope=exec:notebook";
      host: kueyen-lsp.lsst.codes
      tls:
        cluster_issuer: cert-issuer-letsencrypt-dns
        secret: nublado-tls-secret
        tls_host: kueyen-lsp.lsst.codes


  mountpoints: |
    [
      { "disabled": true,
        "mountpoint": "/example -- if it doesn't start with '/' we add it",
        "fileserver-host": "omit to use Hub settings",
        "fileserver-export": "defaults to '/exports<mountpoint>'",
        "mode": "rw or ro, defaults to 'ro'",
        "options": "mount options, e.g. 'local_lock=all'"
      },
      {
        "mountpoint": "/home",
        "mode": "rw",
        "fileserver-host": "ddn-nfs.ls.lsst.org",
        "fileserver-export": "/lsstdata/user/staff/jhome"
      },
      {
        "disabled": true,
        "mountpoint": "/datasets",
        "fileserver-host": "ddn-nfs.ls.lsst.org",
        "fileserver-export": "/lsstdata/user/precursor_data/datasets"
      },
      {
        "mountpoint": "/project",
        "mode": "rw",
        "fileserver-host": "ddn-nfs.ls.lsst.org",
        "fileserver-export": "/lsstdata/user/staff/project"
      },
      {
        "mountpoint": "/scratch",
        "mode": "rw",
        "fileserver-host": "ddn-nfs.ls.lsst.org",
        "fileserver-export": "/lsstdata/user/staff/scratch"
      },
      {
        "disabled": true,
        "mountpoint": "/readonly/auxtel/repo",
        "mode": "ro",
        "fileserver-host": "atarchiver.cp.lsst.org",
        "fileserver-export": "/butler/repo"
      },
      {
        "disabled": true,
        "mountpoint": "/readonly/comcam",
        "mode": "ro",
        "fileserver-host": "comcam-arctl01.ls.lsst.org",
        "fileserver-export": "/lsstdata/base/comcam"
      }
    ]

  signing_certificate: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmNTF9k7R+KzAGsKkpsnh
    yy4nYbWR50xEbv5qguZjxAvlB3qhaO3WPigFJhg8a22dcxaHZOu7u+/ALdITb6J6
    YZkqBs0bVoUiDRm+JlKxASmtHSBT0q5ZYp//TPETtykuiXvpKIs9Jywd62n0K1sS
    IlIc1JEMibMF9jn0B1K0TYRjsLoQCxA7xzNygAeQNTdvc8dAZtjnSdfEkyGr+vy8
    UFdVDnqSnCdD/T5Pizrs2uEkvQM4otSGTsBuesuYZBRqW5wRv9z0k7L4VXN8fKCz
    s9JZf5xrYISSTv+6rkmugsCBw35G2vfvpDbY22zlrJyDPsul5NBi5O4mMzY8jLTk
    rwIDAQAB
    -----END PUBLIC KEY-----

pull-secret:
  enabled: true
  path: secret/k8s_operator/kueyen-lsp.lsst.codes/pull-secret
