nublado:
  fqdn: gold-leader.lsst.codes

  oauth_provider: 'jwt'

  hub:
    image: 'lsstsqre/cbanek-exp-hub:latest'

  wf:
    no_verify_signature: 'true'
    no_verify_audience: 'true'

  lab:
    restrict_nodes: 'true'

    image:
      #repo_host: 'ts-dockerhub.lsst.org'
      #repo_owner: 'test'
      #experimentals: 2
      #dailies: 2
      cachefile: '/home/jovyan/repo-cache.json'

    resources:
      nodejs_max_mem: '6144'
      mb_per_cpu: 2048

  routes:
    soda: '/api/image/soda'
    external:
      instance: 'https://gold-leader.lsst.codes'

  dask:
    restrict_nodes: 'true'

  vault_secrets:
    enabled: true
    path: secret/k8s_operator/gold-leader.lsst.codes/nublado

  proxy:
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/auth-request-redirect: $request_uri
        nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Token
        nginx.ingress.kubernetes.io/auth-signin: https://gold-leader.lsst.codes/login
        nginx.ingress.kubernetes.io/auth-url: https://gold-leader.lsst.codes/auth?scope=exec:notebook
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Forwarded-Port 443;
          proxy_set_header X-Forwarded-Path /nb;
          auth_request_set $auth_token $upstream_http_x_auth_request_token;
          proxy_set_header X-Portal-Authorization "Bearer $auth_token";
          error_page 403 = "/auth/forbidden?scope=exec:notebook";

  mountpoints: |
    [
      { "disabled": true,
        "mountpoint": "/example -- if it doesn't start with '/' we add it",
        "fileserver-host": "omit to use Hub settings",
        "fileserver-export": "defaults to '/exports<mountpoint>'",
        "mode": "rw or ro, defaults to 'ro'",
        "options": "mount options, e.g. 'local_lock=all'"
      },
      {
       "mountpoint": "/home",
        "mode": "rw",
        "fileserver-host": "10.128.0.49",
        "fileserver-export": "/exports/home"
      },
      {
        "mountpoint": "/datasets",
        "fileserver-host": "10.128.0.49",
        "fileserver-export": "/exports/datasets"
      },
      {
        "mountpoint": "/project",
        "mode": "rw",
        "fileserver-host": "10.128.0.49",
        "fileserver-export": "/exports/project"
      },
      {
        "mountpoint": "/scratch",
        "mode": "rw",
        "fileserver-host": "10.128.0.49",
        "fileserver-export": "/exports/scratch"
      }
    ]
