nublado:
  pull_secret: 'pull-secret'
  fqdn: tucson-teststand.lsst.codes
  debug: 'true'
  oauth_provider: 'jwt'
  gafaelfawr_secrets_path: 'secret/k8s_operator/tucson-teststand.lsst.codes/gafaelfawr'

  hub:
    image: 'lsstsqre/sciplat-hub:latest'
    persistent_home: false

  wf:
    ingress_ui:
      annotations:
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Token
        nginx.ingress.kubernetes.io/auth-signin: "https://tucson-teststand.lsst.codes/login"
        nginx.ingress.kubernetes.io/auth-url: "https://tucson-teststand.lsst.codes/auth?scope=exec:notebook"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Forwarded-Port 443;
          proxy_set_header X-Forwarded-Path /workflow;
          auth_request_set $auth_token $upstream_http_x_auth_request_token;
          proxy_set_header X-Portal-Authorization "Bearer $auth_token";
          error_page 403 = "/auth/forbidden?scope=exec:notebook";

  lab:
    cull_timeout: 604800
    restrict_nodes: 'true'
    enable_multus: 'true'
    dds_domain: 'tucson'
    dds_partition_prefix: 'tucson'
    dds_interface: 'net1'
    image:
      experimentals: 0
      dailies: 0
      weeklies: 3
      releases: 1
      cachefile: '/home/jovyan/repo-cache.json'
      repo_name: 'tts-sal-sciplat-lab'


    resources:
      nodejs_max_mem: '6144'
      mb_per_cpu: 2048

  routes:
    soda: '/api/image/soda'
    external:
      instance: 'https://tucson-teststand.lsst.codes'

  dask:
    restrict_nodes: 'true'
    max_workers: 50

  vault_secrets:
    enabled: true
    path: secret/k8s_operator/tucson-teststand.lsst.codes/nublado

  proxy:
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/auth-method: GET
        nginx.ingress.kubernetes.io/auth-signin: "https://tucson-teststand.lsst.codes/login"
        nginx.ingress.kubernetes.io/auth-url: "https://tucson-teststand.lsst.codes/auth?scope=exec:notebook"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Forwarded-Port 443;
          proxy_set_header X-Forwarded-Path /nb;
          auth_request_set $auth_token $upstream_http_x_auth_request_token;
          proxy_set_header X-Portal-Authorization "Bearer $auth_token";
          error_page 403 = "/auth/forbidden?scope=exec:notebook";
      host: tucson-teststand.lsst.codes
      tls:
        cluster_issuer: cert-issuer-letsencrypt-dns
        secret: nublado-tls-secret
        tls_host: tucson-teststand.lsst.codes


  mountpoints: |
    [
      { "disabled": true,
        "mountpoint": "/example -- if it doesn't start with '/' we add it",
        "fileserver-host": "omit to use Hub settings",
        "fileserver-export": "defaults to '/exports<mountpoint>'",
        "mode": "rw or ro, defaults to 'ro'",
        "options": "mount options, e.g. 'local_lock=all'"
      },
      {
       "mountpoint": "/home",
        "mode": "rw",
        "fileserver-host": "nfs01.tu.lsst.org",
        "fileserver-export": "/data/exports-lsp/home"
      },
      {
        "mountpoint": "/datasets",
        "fileserver-host": "nfs01.tu.lsst.org",
        "fileserver-export": "/data/exports-lsp/datasets"
      },
      {
        "mountpoint": "/project",
        "mode": "rw",
        "fileserver-host": "nfs01.tu.lsst.org",
        "fileserver-export": "/data/exports-lsp/project"
      },
      {
        "mountpoint": "/scratch",
        "mode": "rw",
        "fileserver-host": "nfs01.tu.lsst.org",
        "fileserver-export": "/data/exports-lsp/scratch"
      }
    ]

  signing_certificate: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3tO1/yRfJugEN73S7UDy
    hy0HnjvzHa9DfR/aq43MntxqDAyaqXmEwMHDoIE2NGtI6wFabNlk9M5ljtzVcTXB
    dELxo+upzxTlqjLWJYrwgDHPPdsS8Zlps7XpiAPmLq/aI+o2mG31WgTUkyW3+fZ+
    NhT7TESvjFj9vnL1SmE2ccmvR09wkWeVNCMUlYa/Ix+2mG49V5wOjLPVTBPsXlqy
    aXyvsp/dLi6MGAjavsGASOK84Fk/IGOpdv5kGypfwm82FJ6zRZwMAku2ApKBvNQ5
    0iuSs3v/JhXrIARtGXYRrJfYfbMgKQv237a3TTo6TadcR+1TOVWvJG13eYNYNOjp
    LwIDAQAB
    -----END PUBLIC KEY-----

pull-secret:
  enabled: true
  path: secret/k8s_operator/tucson-teststand.lsst.codes/pull-secret
