argo-cd:
  redis:
    enabled: true

  server:
    ingress:
      enabled: true
      hosts:
        - "summit-lsp.lsst.codes"
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: "/$2"
      paths:
        - /argo-cd(/|$)(.*)

    extraArgs:
      - "--basehref=/argo-cd"
      - "--insecure=true"

    config:
      helm.repositories: |
        - url: https://lsst-sqre.github.io/charts/
          name: lsst-sqre
        - url: https://ricoberger.github.io/helm-charts/
          name: ricoberger
        - url: https://kubernetes.github.io/ingress-nginx/
          name: ingress-nginx

pull-secret:
  enabled: true
  path: secret/k8s_operator/summit-lsp.lsst.codes/pull-secret
