argo-cd:
  redis:
    enabled: true

  server:
    ingress:
      enabled: true
      hosts:
        - "rsp.lsst.ac.uk"
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: "/$2"
      paths:
        - /argo-cd(/|$)(.*)

    extraArgs:
      - "--basehref=/argo-cd"
      - "--insecure=true"

    config:
      helm.repositories: |
        - url: https://github.com/lsst-sqre/charts
          name: lsst-sqre
        - url: https://ricoberger.github.io/helm-charts/
          name: ricoberger
        - url: https://kubernetes.github.io/ingress-nginx/
          name: ingress-nginx
        - url: https://charts.helm.sh/stable
          name: stable
pull-secret:
  enabled: true
  path: secret/k8s_operator/roe/pull-secret



