exposurelog:
  pull_secret: pull-secret

  site_id: bleed
  # Use the built-in toy registry, so set neither butler_uri_1 nor butler_uri_2

  ingress:
    enabled: true
    annotations: {}
    #   kubernetes.io/ingress.class: nginx
    #   kubernetes.io/tls-acme: "true"
    hosts:
      - host: bleed.lsst.codes
        paths:
          - /exposurelog
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

vault_path: secret/k8s_operator/bleed.lsst.codes/postgres

pull-secret:
  enabled: true
  path: secret/k8s_operator/bleed.lsst.codes/pull-secret
