exposurelog:

  nfs_path_1: /lsstdata/base/comcam  # Mounted as /volume_1
  nfs_server_1: comcam-arctl01.cp.lsst.org
  butler_uri_1: /volume_1/oods/gen3butler/repo

  ingress:
    enabled: true
    annotations: {}
    #   kubernetes.io/ingress.class: nginx
    #   kubernetes.io/tls-acme: "true"
    hosts:
      - host: summit-lsp.lsst.codes
        paths:
          - /exposurelog
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

vault_path: secret/k8s_operator/summit-lsp.lsst.codes/postgres
