cachemachine:
  host: "summit-lsp.lsst.codes"

  ingress:
    enabled: true
    hosts:
      - host: summit-lsp.lsst.codes
        paths: ["/cachemachine"]

  vault_secrets:
    enabled: true
    path: "secret/k8s_operator/summit-lsp.lsst.codes/pull-secret"

  autostart:
    jupyter: |
      {
        "name": "jupyter",
        "labels": {},
        "repomen": [
          {
            "type": "RubinRepoMan",
            "registry_url": "registry.hub.docker.com",
            "repo": "lsstsqre/summit-sal-sciplat-lab",
            "recommended_tag": "recommended",
            "num_releases": 1,
            "num_weeklies": 3,
            "num_dailies": 0
          }
        ]
      }
