cachemachine:
  host: "data-dev.lsst.cloud"

  ingress:
    enabled: true
    hosts:
      - host: data-dev.lsst.cloud
        paths: ["/cachemachine"]

  vault_secrets:
    enabled: true
    path: "secret/k8s_operator/data-dev.lsst.cloud/pull-secret"

  autostart:
    jupyter: |
      {
        "name": "jupyter",
        "labels": {},
        "repomen": [
          {
            "type": "RubinRepoMan",
            "registry_url": "registry.hub.docker.com",
            "repo": "lsstsqre/sciplat-lab",
            "recommended_tag": "recommended",
            "num_releases": 1,
            "num_weeklies": 2,
            "num_dailies": 3
          }
        ]
      }
