cachemachine:
  host: "rspdev.ddns.net"

  image:
    tag: "1.0.0"

  ingress:
    enabled: true
    hosts:
      - host: minikube.lsst.codes
        paths: ["/cachemachine"]

  vault_secrets:
    enabled: true
    path: "secret/k8s_operator/roe/cachemachine"
