firefly:
  pull_secret: 'pull-secret'

  ingress:
    host: "data-dev.lsst.cloud"
    annotations:
      nginx.ingress.kubernetes.io/auth-method: GET
      nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Name,X-Auth-Request-Email,X-Auth-Request-Token
      nginx.ingress.kubernetes.io/auth-signin: "https://data-dev.lsst.cloud/login"
      nginx.ingress.kubernetes.io/auth-url: "https://data-dev.lsst.cloud/auth?scope=exec:portal&delegate_to=portal&delegate_scope=read:tap"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-Path /portal/app;

  max_jvm_size: "7G"

  resources:
    limits:
      memory: 8Gi

  secrets:
    enabled: false

  vault_secrets:
    enabled: true
    path: secret/k8s_operator/data-dev.lsst.cloud/portal

  redis:
    resources:
      limits:
        memory: 20Mi

pull-secret:
  enabled: true
  path: secret/k8s_operator/data-dev.lsst.cloud/pull-secret
