firefly:
  pull_secret: 'pull-secret'
  image:
    #tag: "rc-2.1.0-2"
    tag: "1.1.1"
    
  ingress:
    host: 'rsp.lsst.ac.uk'
    annotations:
      nginx.ingress.kubernetes.io/auth-method: GET
      nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Uid, X-Auth-Request-Token
      nginx.ingress.kubernetes.io/auth-signin: "https://rsp.lsst.ac.uk/login"
      nginx.ingress.kubernetes.io/auth-url: "https://rsp.lsst.ac.uk/auth?scope=exec:portal"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-Path /portal/app;
  max_jvm_size: "7G"


  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: portal

  resources:
    limits:
      memory: 8Gi
      
  secrets:
    enabled: false

  vault_secrets:
    enabled: true
    path: 'secret/k8s_operator/roe/portal'

  securityContext:
    runAsUser: 101
    runAsGroup: 102

  redis:
    resources:
      limits:
        memory: 20Mi

pull-secret:
  enabled: true
  path: secret/k8s_operator/roe/pull-secret
