nublado2:
  jupyterhub:
    debug:
      enabled: true

    ingress:
      hosts: ["data-int.lsst.cloud"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://data-int.lsst.cloud/login"
        nginx.ingress.kubernetes.io/auth-url: "http://gafaelfawr.gafaelfawr.svc.cluster.local:8080/auth?scope=exec:notebook&notebook=true"

    hub:
      baseUrl: '/nb'

  config:
    base_url: "https://data-int.lsst.cloud"
    butler_secret_path: "secret/k8s_operator/data-int.lsst.cloud/butler-secret"
    lab_environment:
      PGPASSFILE: "/opt/lsst/software/jupyterlab/butler-secret/postgres-credentials.txt"
      AWS_SHARED_CREDENTIALS_FILE: "/opt/lsst/software/jupyterlab/butler-secret/aws-credentials.ini"
      S3_ENDPOINT_URL: "https://storage.googleapis.com"
    volumes:
      - name: datasets
        nfs:
          path: /share1/datasets
          server: 10.22.240.130
      - name: home
        nfs:
          path: /share1/home
          server: 10.22.240.130
      - name: project
        nfs:
          path: /share1/project
          server: 10.22.240.130
      - name: scratch
        nfs:
          path: /share1/scratch
          server: 10.22.240.130
    volume_mounts:
      - name: datasets
        mountPath: /datasets
      - name: home
        mountPath: /home
      - name: project
        mountPath: /project
      - name: scratch
        mountPath: /scratch

  vault_secret_path: "secret/k8s_operator/data-int.lsst.cloud/nublado2"
