nublado2:
  jupyterhub:
    debug:
      enabled: true

    ingress:
      hosts: ["summit-lsp.lsst.codes"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://summit-lsp.lsst.codes/login"
        nginx.ingress.kubernetes.io/auth-url: "http://gafaelfawr.gafaelfawr.svc.cluster.local:8080/auth?scope=exec:notebook&notebook=true"

    hub:
      baseUrl: '/nb'

    singleuser:
      extraAnnotations:
        k8s.v1.cni.cncf.io/networks: "kube-system/macvlan-conf"
      initContainers:
        - name: "multus-init"
          image: "lsstit/ddsnet4u:latest"
          securityContext:
            privileged: true

  config:
    base_url: "https://summit-lsp.lsst.codes"
    butler_secret_path: "secret/k8s_operator/summit-lsp.lsst.codes/butler-secret"
    lab_environment:
      LSST_DDS_INTERFACE: net1
      LSST_DDS_PARTITION_PREFIX: summit
    volumes:
      - name: home
        nfs:
          path: /jhome
          server: nfs1.cp.lsst.org
      - name: project
        nfs:
          path: /project
          server: nfs1.cp.lsst.org
      - name: scratch
        nfs:
          path: /scratch
          server: nfs1.cp.lsst.org
      - name: auxtel
        nfs:
          path: /lsstdata
          server: atarchiver.cp.lsst.org
          readOnly: true
      - name: comcam
        nfs:
          path: /lsstdata
          server: comcam-arctl01.cp.lsst.org
          readOnly: true
      - name: other
        nfs:
          path: /lsstdata
          server: nfs1.cp.lsst.org
          readOnly: true
      - name: latiss
        nfs:
          path: /repo/LATISS
          server: atarchiver.cp.lsst.org
      - name: base-auxtel
        nfs:
          path: /lsstdata/base/auxtel
          server: atarchiver.cp.lsst.org
          readOnly: true
      - name: lsstcomcam
        nfs:
          path: /repo/LSSTComCam
          server: comcam-arctl01.cp.lsst.org
      - name: base-comcam
        nfs:
          path: /lsstdata/base/comcam
          server: comcam-arctl01.cp.lsst.org
          readOnly: true
    volume_mounts:
      - name: home
        mountPath: /home
      - name: project
        mountPath: /project
      - name: scratch
        mountPath: /scratch
      - name: auxtel
        mountPath: /readonly/lsstdata/auxtel
        readOnly: true
      - name: comcam
        mountPath: /readonly/lsstdata/comcam
        readOnly: true
      - name: other
        mountPath: /readonly/lsstdata/other
        readOnly: true
      - name: latiss
        mountPath: /repo/LATISS
      - name: base-auxtel
        mountPath: /data/lsstdata/base/auxtel
        readOnly: true
      - name: lsstcomcam
        mountPath: /repo/LSSTComCam
      - name: base-comcam
        mountPath: /data/lsstdata/base/comcam
        readOnly: true

  vault_secret_path: "secret/k8s_operator/summit-lsp.lsst.codes/nublado2"
