nublado2:
  jupyterhub:
    debug:
      enabled: true
    singleuser:
      storage:
        type: none
        extraVolumes:
          - name: tmp
            emptyDir: {}
          - name: lab-environment
            configMap:
              defaultMode: 420
              name: lab-environment
          - name: passwd
            configMap:
              defaultMode: 420
              name: passwd
          - name: group
            configMap:
              defaultMode: 420
              name: group
          - name: shadow
            configMap:
              defaultMode: 384
              name: shadow
          - name: gshadow
            configMap:
              defaultMode: 384
              name: gshadow
        extraVolumeMounts:
          - name: lab-environment
            mountPath: /opt/lsst/software/jupyterlab/environment
          - name: tmp
            mountPath: /tmp
          - name: passwd
            mountPath: /etc/passwd
            readOnly: true
            subPath: passwd
          - name: group
            mountPath: /etc/group
            readOnly: true
            subPath: group
          - name: shadow
            mountPath: /etc/shadow
            readOnly: true
            subPath: shadow
          - name: gshadow
            mountPath: /etc/gshadow
            readOnly: true
            subPath: gshadow

    ingress:
      hosts: ["minikube.lsst.codes"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://minikube.lsst.codes/login"

  config:
    base_url: "https://minikube.lsst.codes"
    auto_repo_urls: "https://github.com/lsst-sqre/notebook-demo"

  vault_secret_path: "secret/k8s_operator/minikube.lsst.codes/nublado2"
  gafaelfawr_secret_path: "secret/k8s_operator/minikube.lsst.codes/gafaelfawr"
