nublado2:
  jupyterhub:
    debug:
      enabled: true

    ingress:
      hosts: ["base-lsp.lsst.codes"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://base-lsp.lsst.codes/login"
        nginx.ingress.kubernetes.io/auth-url: "http://gafaelfawr.gafaelfawr.svc.cluster.local:8080/auth?scope=exec:notebook&notebook=true"

    hub:
      baseUrl: '/nb'

    singleuser:
      extraAnnotations:
        k8s.v1.cni.cncf.io/networks: "kube-system/macvlan-conf"
      initContainers:
        - name: "multus-init"
          image: "lsstit/ddsnet4u:latest"
          securityContext:
            privileged: true

  config:
    base_url: "https://base-lsp.lsst.codes"
    butler_secret_path: "secret/k8s_operator/base-lsp.lsst.codes/butler-secret"
    lab_environment:
      LSST_DDS_INTERFACE: net1
      LSST_DDS_PARTITION_PREFIX: base
    volumes:
      - name: home
        nfs:
          path: /lsstdata/user/staff/jhome
          server: ddn-nfs.ls.lsst.org
      - name: project
        nfs:
          path: /lsstdata/user/staff/project
          server: ddn-nfs.ls.lsst.org
      - name: scratch
        nfs:
          path: /lsstdata/user/staff/scratch
          server: ddn-nfs.ls.lsst.org
    volume_mounts:
      - name: home
        mountPath: /home
      - name: project
        mountPath: /project
      - name: scratch
        mountPath: /scratch

  vault_secret_path: "secret/k8s_operator/base-lsp.lsst.codes/nublado2"
