nublado2:
  jupyterhub:
    debug:
      enabled: true

    hub:
      image:
        name: lsstsqre/nublado2
        tag: "1.0.0"

    singleuser:
      storage:
        type: none

    ingress:
      hosts: ["minikube.lsst.codes"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://minikube.lsst.codes/login"
        nginx.ingress.kubernetes.io/auth-url: "http://gafaelfawr-service.gafaelfawr.svc.cluster.local:8080/auth?scope=exec:notebook"

  vault_secret_path: "secret/k8s_operator/minikube.lsst.codes/nublado2"
