nublado2:
  jupyterhub:
    debug:
      enabled: true

    hub:
      image:
        name: lsstsqre/nublado2
        tag: "master"

    singleuser:
      storage:
        type: none
        extraVolumes:
          - name: datasets
            nfs:
              path: /share1/datasets
              server: 10.87.86.26
          - name: home
            nfs:
              path: /share1/home
              server: 10.87.86.26
          - name: project
            nfs:
              path: /share1/project
              server: 10.87.86.26
          - name: scratch
            nfs:
              path: /share1/scratch
              server: 10.87.86.26
        extraVolumeMounts:
          - name: datasets
            mountPath: /datasets
          - name: home
            mountPath: /home
          - name: project
            mountPath: /project
          - name: scratch
            mountPath: /scratch


    ingress:
      hosts: ["data-dev.lsst.cloud"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://data-dev.lsst.cloud/login"

  config:
    base_url: "https://data-dev.lsst.cloud/"

    user_resources:
      - apiVersion: v1
        kind: Namespace
        metadata:
          name: "{{user_namespace}}"
      - apiVersion: v1
        kind: ConfigMap
        metadata:
          name: lab-environment
          namespace: "{{user_namespace}}"
        data:
          EXTERNAL_INSTANCE_URL: "{{base_url}}"
          FIREFLY_ROUTE: /portal/app
          HUB_ROUTE: /n2
          JS9_ROUTE: /js9
          API_ROUTE: /api
          TAP_ROUTE: /api/tap
          SODA_ROUTE: /api/image/soda
          WORKFLOW_ROUTE: /wf
          AUTO_REPO_URLS: https://github.com/lsst-sqre/notebook-demo
          EXTERNAL_GROUPS: "{{external_groups}}"
          EXTERNAL_UID: "{{uid}}"
          ACCESS_TOKEN: "{{token}}"

  vault_secret_path: "secret/k8s_operator/data-dev.lsst.cloud/nublado2"
