 nublado2:
  jupyterhub:
    debug:
      enabled: true

    ingress:
      hosts: ["rsp.lsst.ac.uk"]
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: "https://rsp.lsst.ac.uk/login"

  config:
    base_url: "rsp.lsst.ac.uk"

    volumes:
      - name: home
        emptyDir: {}
    volume_mounts:
      - name: home
        mountPath: /home

  vault_secret_path: "secret/k8s_operator/roe/nublado2"
  gafaelfawr_secret_path: "secret/k8s_operator/roe/gafaelfawr"
