landing-page:
  pull_secret: 'pull-secret'
  motd_url: https://raw.githubusercontent.com/lsst-dm/lsp-landing-page/master/motd/integration.md
  host: "rsp.lsst.ac.uk
  image:
    tag: "3.0.1"

pull-secret:
  enabled: true
  path: secret/k8s_operator/roe/pull-secret
