landing-page:
  pull_secret: 'pull-secret'
  motd_url: https://raw.githubusercontent.com/lsst-dm/lsp-landing-page/master/motd/integration.md
  host: "data-dev.lsst.cloud"
  image:
    tag: "3.0.1"
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: cert-issuer-letsencrypt-dns
    tls:
      - secretName: landing-page-tls
        hosts:
          - "data-dev.lsst.cloud"

pull-secret:
  enabled: true
  path: secret/k8s_operator/data-dev.lsst.cloud/pull-secret
